[pytest]
testpaths = tests
addopts =
    -v
    --html=reports/report.html
    --self-contained-html
    --tb=short
    --metadata "Project" "Selenium Suite — saucedemo.com"
    --metadata "Environment" "QA"
    --metadata "Browser" "Chrome"
    --metadata "Tester" "CDAC"
    --metadata "Base URL" "https://www.saucedemo.com"
markers =
    smoke:      Quick sanity checks — run on every commit
    regression: Full regression suite — run nightly
    login:      Login-related tests
    inventory:  Product and cart tests
    checkout:   Checkout flow tests
    navigation: Navigation and logout tests